### PR TITLE
Fix compilation for maybe_uninit && !integer128

### LINKED ISSUE #18: ryu 1.0.1 fails to build with emscripten
```
error[E0308]: mismatched types
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:222:15
    |
222 |             { vp_uninit.as_mut_ptr() },
    |               ^^^^^^^^^^^^^^^^^^^^^^ expected &mut u64, found *-ptr
    |
    = note: expected type `&mut u64`
               found type `*mut u64`

error[E0308]: mismatched types
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:226:15
    |
226 |             { vm_uninit.as_mut_ptr() },
    |               ^^^^^^^^^^^^^^^^^^^^^^ expected &mut u64, found *-ptr
    |
    = note: expected type `&mut u64`
               found type `*mut u64`

error[E0308]: mismatched types
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:273:15
    |
273 |             { vp_uninit.as_mut_ptr() },
    |               ^^^^^^^^^^^^^^^^^^^^^^ expected &mut u64, found *-ptr
    |
    = note: expected type `&mut u64`
               found type `*mut u64`

error[E0308]: mismatched types
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.1/src/d2s.rs:277:15
    |
277 |             { vm_uninit.as_mut_ptr() },
    |               ^^^^^^^^^^^^^^^^^^^^^^ expected &mut u64, found *-ptr
    |
    = note: expected type `&mut u64`
               found type `*mut u64`

```

https://github.com/LiveSplit/livesplit-core/pull/257/checks?check_run_id=259206571

Seems like it has cfg(maybe_uninit) but not cfg(integer128), which then uses MaybeUninit, but the signature of mul_shift_all uses mutable references then.

### PR DESCRIPTION
**Pull request by dtolnay**
Fixes #18.

### CODE REVIEW

File: src/d2s.rs [hunk 1]
```diff
@@ -85,21 +85,27 @@ fn mul_shift_all(
     let lo2 = lo.wrapping_add(mul.0);
     let mid2 = mid.wrapping_add(mul.1).wrapping_add((lo2 < lo) as u64);
     let hi2 = hi.wrapping_add((mid2 < mid) as u64);
-    *vp = shiftright128(mid2, hi2, j - 64 - 1);
+    unsafe {
+        ptr::write(vp, shiftright128(mid2, hi2, j - 64 - 1));
```
Comment (bjorn3) [inline src/d2s.rs]: This function is safe, so it should not write to arbitrary pointers.

Comment (dtolnay) [reply src/d2s.rs]: Thanks! Good catch.
